### PR TITLE
migrate to apollo-boost

### PR DESCRIPTION
**Pull request by ascott1**
👋 @adamsoffer. Thanks for this great package. I'm teaching React/Next & GraphQL and find the use of this package to be much easier for students to understand than the HOC in the official next examples.

This _should_ address #23 by migrating from the deprecated `apollo-client-preset` to `apollo-boost`.

### CODE REVIEW

**Comment by adamsoffer** [comment]
Thanks @ascott1. Appreciate the kind words and great knowing this will help your students.

PR looks great. Merging now.

p.s. I'm from New Haven as well 🙌

**Comment by ascott1** [comment]
> p.s. I'm from New Haven as well 🙌

Small world! I'm currently using this library when building out the web app for my next [O'Reilly book](https://www.jseverywhere.io/). I would love to chat sometime.

**Comment by ascott1** [comment]
@adamsoffer I thought this was a simple 1:1 dependency swap, but it looks like it causes issues with all of the example implementations. I haven't had a chance to dig in too much, but my theory is that it's caused by apollo-boost's [different configuration options](https://www.apollographql.com/docs/react/essentials/get-started#configuration). 

In the meantime it might be better to roll this back and look at importing the packages individually, rather than via boost. Sorry!!!

**Comment by adamsoffer** [comment]
Seems like this is actually [a bug in `apollo-boost`](https://github.com/apollographql/apollo-client/issues/4843). I downgraded and froze the `apollo-boost` dep to `0.3.1` and confirmed it works with the next-apollo-example now :) Thanks again.


> Small world! I'm currently using this library when building out the web app for my next [O'Reilly book](https://www.jseverywhere.io/). I would love to chat sometime.

That book looks awesome! Would love to chat. You should come through the Digital Surgeons office sometime at District :) My email is adam @ soffer dot dev

**Comment by ascott1** [comment]
Ah, good catch!

**Pull request merged**
