### PR TITLE
TypeScript support (#71)

### LINKED ISSUE #71: Rewrite in Typescript
If anyone wants to take a stab at this, feel free to submit a PR!

### PR DESCRIPTION
**Pull request by ecklf**
closes #71 

Before merging I would like to talk about the following lines that needed type overwrites:

1) https://github.com/impulse/next-apollo/blob/master/src/withApollo.tsx#L58
It seems there is no `toJSON()` method. Is this still relevant for apollo client v3?

2) https://github.com/impulse/next-apollo/blob/master/src/withApollo.tsx#L220
It seems `ssrMode` cannot be accessed from an ApolloClient instance? Wouldn't it be the better solution to do:

```diff
const apolloClient = new ApolloClient({
+ ssrMode: typeof window === "undefined",
  uri: "https://api.graph.cool/simple/v1/cixmkt2ul01q00122mksg82pn",
  cache: new InMemoryCache()
});
```

3) https://github.com/impulse/next-apollo/blob/master/src/withApollo.tsx#L182
Maybe someone knows how to address this type error.

Result in VSCode:
image

### CODE REVIEW

**Comment by adamsoffer** [comment]
Wow thanks @impulse ! This looks great. I'm on vacation at the moment but I'll get try and review and test this ASAP.

**Comment by adamsoffer** [comment]
Hey @impulse. This looks great. Regarding your questions...

> It seems there is no toJSON() method. Is this still relevant for apollo client v3?

Not sure TBH

> It seems ssrMode cannot be accessed from an ApolloClient instance?

Your solution LGTM

> Maybe someone knows how to address this type error. 

Not sure about this one either.

I'm good to merge this and publish whenever you address the above. Thanks again for this epic PR.

**Comment by ecklf** [comment]
@adamsoffer I think we can merge this for now in the scope of converting things to TypeScript. I don't want to introduce anything breaking, so I guess it would be better to work out and extensively test the things I've mentioned in future PRs.

**Comment by TheBit** [comment]
Thanx guys!

**Pull request merged**
