### PR TITLE
Pass ctx to apolloClient

### PR DESCRIPTION
**Pull request by alyavasilyeva**
Related to #60 
If withData receives function, pass ctx to ApolloClient

### CODE REVIEW

**Review by adamsoffer — APPROVED** [review]
Perfect! Nice and simple. Thanks @alyavasilyeva

**Comment by adamsoffer** [comment]
@alyavasilyeva - I actually just tested these changes with the [`next-apollo-example`](https://github.com/adamsoffer/next-apollo-example) and it seems these changes breaks ssr. Getting the following warnings: `index.js:1 Warning: Expected server HTML to contain a matching <div> in <div>.`

**Comment by adamsoffer** [comment]
Here's how I'm passing in the client in the example:

```js
const config = {
  link: new HttpLink({
    uri: "https://api.graph.cool/simple/v1/cixmkt2ul01q00122mksg82pn"
  })
};

const client = new ApolloClient(config)

export default withData(client);
```

**Comment by alyavasilyeva** [comment]
@adamsoffer oh, that's my mistake! I wrote a misleading description, at the moment it works like this: 
```
const config = ctx => ({
  link: new HttpLink({
    uri: "https://api.graph.cool/simple/v1/cixmkt2ul01q00122mksg82pn",
    headers: {
      Cookie: !process.browser && ctx && ctx.req && ctx.req.headers['cookie'],
    },
  }),
});

export default withData(client);
```
This solution was enough for authentication in our project, and I didn't check it with ApolloClient, but if we still need to be able to use ApolloClient in withData, let me check it again!

**Pull request merged**
